#!/usr/bin/env python3
"""
gen-config.py
=============
Write config.js for the RCA Triage dashboard from environment variables.

The dashboard is a static page served locally (python -m http.server), so it
can't read the environment itself. This script bridges that gap: it reads the
LiteLLM gateway settings (and optional dial defaults) from the environment and
emits a config.js that the page loads at boot.

Env vars (see env.example):
    LITELLM_MODEL          model name, used verbatim (e.g. databricks-claude-sonnet-4)
    LITELLM_BASE_URL       OpenAI-compatible gateway root (e.g. https://host/v1)
    LITELLM_KEY            gateway key
    RCA_SEVERITY_DEFAULT   optional, default 5
    RCA_BLEND_DEFAULT      optional, default 5

Usage:
    export $(grep -v '^#' .env | xargs)   # or however you load .env
    python gen-config.py                  # writes ./config.js

If the three model vars are absent, config.js is still written with blank model
fields — the dashboard will probe on boot and hide the model UI if it can't
connect. Nothing here contacts the network.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

CLASSES = ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8"]
OUT = Path(__file__).resolve().parent / "config.js"


def _int_env(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None or raw.strip() == "":
        return default
    try:
        return int(raw)
    except ValueError:
        print(f"[gen-config] {name}={raw!r} is not an int; using {default}.",
              file=sys.stderr)
        return default


def main() -> int:
    model = os.getenv("LITELLM_MODEL", "").strip()
    base_url = os.getenv("LITELLM_BASE_URL", "").strip().rstrip("/")
    key = os.getenv("LITELLM_KEY", "").strip()

    sev_default = _int_env("RCA_SEVERITY_DEFAULT", 5)
    blend_default = _int_env("RCA_BLEND_DEFAULT", 5)

    cfg = {
        "model": model,
        "baseUrl": base_url,
        "key": key,
        "severityDefault": sev_default,
        "blendDefault": blend_default,
        "severity": {c: sev_default for c in CLASSES},
        "blend": {c: blend_default for c in CLASSES},
    }

    banner = (
        "// config.js — GENERATED by gen-config.py from your environment.\n"
        "// Do not commit (it may hold a real key). Regenerate any time by\n"
        "// re-running: python gen-config.py\n\n"
    )
    OUT.write_text(banner + "window.RCA_CONFIG = " + json.dumps(cfg, indent=2) + ";\n")

    have = bool(model and base_url and key)
    where = "with a full model connection" if have else "WITHOUT model settings (UI will hide model features)"
    print(f"[gen-config] wrote {OUT.name} {where}.", file=sys.stderr)
    if not have:
        missing = [n for n, v in (("LITELLM_MODEL", model),
                                  ("LITELLM_BASE_URL", base_url),
                                  ("LITELLM_KEY", key)) if not v]
        print(f"[gen-config] missing: {', '.join(missing)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
